package com.mtbs3d.minecrift.control;

public enum ViveButtons {
 BUTTON_LEFT_TRIGGER ,
 BUTTON_LEFT_TRIGGER_FULLCLICK,
 BUTTON_LEFT_APPMENU,
 BUTTON_LEFT_TOUCHPAD_UL,
 BUTTON_LEFT_TOUCHPAD_UR,
 BUTTON_LEFT_TOUCHPAD_BL,
 BUTTON_LEFT_TOUCHPAD_BR,
 BUTTON_LEFT_GRIP,
 BUTTON_RIGHT_TRIGGER,
 BUTTON_RIGHT_TRIGGER_FULLCLICK,
 BUTTON_RIGHT_APPMENU,
 BUTTON_RIGHT_TOUCHPAD_UL,
 BUTTON_RIGHT_TOUCHPAD_UR,
 BUTTON_RIGHT_TOUCHPAD_BL,
 BUTTON_RIGHT_TOUCHPAD_BR,
 BUTTON_RIGHT_GRIP,
}



